language: go
go:
  - 1.12.x
before_install:
  - export GO111MODULE=on
script: go test -test.bench=.* -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
